[workspace]
authors = ["GnU-Chan <gnusocute@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "socket-mojo"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
test = "mojo run -I . tests/run_tests.mojo"
bench = "mojo run -I . benchmarks/bench.mojo"

[dependencies]
mojo-compiler = "==1.0.0b3.dev2026061706"
mblack = "==26.5.0.dev2026061706"
