[workspace]
authors = ["luanon404 <luanon404@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "socket-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo run -I . tests/run_tests.mojo"
bench = "mojo run -I . benchmarks/bench.mojo"

[dependencies]
mojo-compiler = "==1.0.0b2.dev2026061006"
